# Contoh untuk nama Rifat ( R dan T)

print(" #######        ###########")
print(" #      #            #     ")
print(" #      #            #     ")
print(" #######             #     ")
print(" #      #            #     ")
print(" #      #            #     ")
print(" #      #            #     ")
print("---------------------------")