print("###########################")
print("#                         #")
print("#     Muhammad Rifat      #")
print("#      2610817210003      #")
print("#                         #")
print("###########################")